In [27]:
import numpy as np

A = np.array(
    [[3, 2, 8, -1],
    [8, 4, -17, 3],
    [6, -2 ,7, 10],
    [-5, 3, 9, 7]]
)
B = np.array(
    [[5], [8], [19] ,[43]]
)

**Calcul des matrices**

In [28]:
np.dot(np.linalg.inv(A), B)

array([[-1.14608905],
       [ 3.93044525],
       [ 0.45415162],
       [ 3.05583634]])

Remplir une matrice : (1, 2, 3, ... 100), (2, 3, 4, ... 101)

In [29]:
tab = [[i + j + 1 for j in range (100)] for i in range(100)]
A = np.array(tab)
print(A)

# invA = np.linalg.inv(A)

[[  1   2   3 ...  98  99 100]
 [  2   3   4 ...  99 100 101]
 [  3   4   5 ... 100 101 102]
 ...
 [ 98  99 100 ... 195 196 197]
 [ 99 100 101 ... 196 197 198]
 [100 101 102 ... 197 198 199]]


3 droites :
d1 passe par (1, 2) dirigée par (8, 2)
d2 passe par (6, -4) dirigée par (7, 17)
d3 passe par (-7, 4) dirigée par (19, -3)

In [30]:
d1 = ([
    [8, 1],
    [2, 2]
])
d2 = ([
    [7, 6],
    [17, -4]
])
d3 = ([
    [19, -7],
    [-3, 4]
])

d1 = np.array(d1)
d2 = np.array(d2)

print(np.dot(np.linalg.inv(d1), d2))

[[-0.21428571  1.14285714]
 [ 8.71428571 -3.14285714]]
